### ISSUE TITLE
在linux下用pyinstall打包的时候会出现如下错误

### ISSUE THREAD

**Issue by ghhccghk** [ChaozhongLiu/DyberPet#10]
打包时候的日志

```

`(DyberPet) ➜  DyberPet git:(main) ✗ pyinstaller -F -w  run_DyberPet.py       
307 INFO: PyInstaller: 5.10.1
307 INFO: Python: 3.9.16 (conda)
312 INFO: Platform: Linux-6.1.30-1-lts-x86_64-with-glibc2.37
312 INFO: wrote /home/ghhc/Desktop/DyberPet/run_DyberPet.spec
317 INFO: UPX is not available.
317 INFO: Extending PYTHONPATH with paths
['/home/ghhc/Desktop/DyberPet']
425 INFO: checking Analysis
425 INFO: Building Analysis because Analysis-00.toc is non existent
425 INFO: Initializing module dependency graph...
426 INFO: Caching module graph hooks...
431 INFO: Analyzing base_library.zip ...
1891 INFO: Loading module hook 'hook-encodings.py' from '/home/ghhc/miniconda3/envs/DyberPet/lib/python3.9/site-packages/PyInstaller/hooks'...
2802 INFO: Loading module hook 'hook-pickle.py' from '/home/ghhc/miniconda3/envs/DyberPet/lib/python3.9/site-packages/PyInstaller/hooks'...
3268 INFO: Loading module hook 'hook-heapq.py' from '/home/ghhc/miniconda3/envs/DyberPet/lib/python3.9/site-packages/PyInstaller/hooks'...
3581 INFO: Caching module dependency graph...
3636 INFO: running Analysis Analysis-00.toc
3655 INFO: Analyzing /home/ghhc/Desktop/DyberPet/run_DyberPet.py
3836 INFO: Loading module hook 'hook-pynput.py' from '/home/ghhc/miniconda3/envs/DyberPet/lib/python3.9/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
4341 INFO: Processing pre-safe import module hook six.moves from '/home/ghhc/miniconda3/envs/DyberPet/lib/python3.9/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-six.moves.py'.
4448 INFO: Loading module hook 'hook-platform.py' from '/home/ghhc/miniconda3/envs/DyberPet/lib/python3.9/site-packages/PyInstaller/hooks'...
4453 INFO: Loading module hook 'hook-apscheduler.py' from '/home/ghhc/miniconda3/envs/DyberPet/lib/python3.9/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
4908 INFO: Loading module hook 'hook-pkg_resources.py' from '/home/ghhc/miniconda3/envs/DyberPet/lib/python3.9/site-packages/PyInstaller/hooks'...
5840 INFO: Loading module hook 'hook-xml.py' from '/home/ghhc/miniconda3/envs/DyberPet/lib/python3.9/site-packages/PyInstaller/hooks'...
5858 INFO: Loading module hook 'hook-sysconfig.py' from '/home/ghhc/miniconda3/envs/DyberPet/lib/python3.9/site-packages/PyInstaller/hooks'...
5898 INFO: Loading module hook 'hook-pytz.py' from '/home/ghhc/miniconda3/envs/DyberPet/lib/python3.9/site-packages/PyInstaller/hooks'...
6015 INFO: Loading module hook 'hook-difflib.py' from '/home/ghhc/miniconda3/envs/DyberPet/lib/python3.9/site-packages/PyInstaller/hooks'...
6336 INFO: Loading module hook 'hook-multiprocessing.util.py' from '/home/ghhc/miniconda3/envs/DyberPet/lib/python3.9/site-packages/PyInstaller/hooks'...
6868 INFO: Processing module hooks...
6948 INFO: Loading module hook 'hook-Xlib.py' from '/home/ghhc/miniconda3/envs/DyberPet/lib/python3.9/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
7774 INFO: Loading module hook 'hook-platformdirs.py' from '/home/ghhc/miniconda3/envs/DyberPet/lib/python3.9/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
7822 INFO: Loading module hook 'hook-packaging.py' from '/home/ghhc/miniconda3/envs/DyberPet/lib/python3.9/site-packages/PyInstaller/hooks'...
7896 INFO: Loading module hook 'hook-PyQt5.QtCore.py' from '/home/ghhc/miniconda3/envs/DyberPet/lib/python3.9/site-packages/PyInstaller/hooks'...
ldd: 警告：你没有执行权限  `/home/ghhc/miniconda3/envs/DyberPet/lib/python3.9/site-packages/PyQt5/QtCore.abi3.so'
8054 INFO: Loading module hook 'hook-PyQt5.QtWidgets.py' from '/home/ghhc/miniconda3/envs/DyberPet/lib/python3.9/site-packages/PyInstaller/hooks'...
ldd: 警告：你没有执行权限  `/home/ghhc/miniconda3/envs/DyberPet/lib/python3.9/site-packages/PyQt5/QtWidgets.abi3.so'
8113 INFO: Loading module hook 'hook-PyQt5.QtMultimedia.py' from '/home/ghhc/miniconda3/envs/DyberPet/lib/python3.9/site-packages/PyInstaller/hooks'...
ldd: 警告：你没有执行权限  `/home/ghhc/miniconda3/envs/DyberPet/lib/python3.9/site-packages/PyQt5/QtMultimedia.abi3.so'
8167 INFO: Loading module hook 'hook-PyQt5.QtGui.py' from '/home/ghhc/miniconda3/envs/DyberPet/lib/python3.9/site-packages/PyInstaller/hooks'...
ldd: 警告：你没有执行权限  `/home/ghhc/miniconda3/envs/DyberPet/lib/python3.9/site-packages/PyQt5/QtGui.abi3.so'
8216 INFO: Loading module hook 'hook-PyQt5.QtNetwork.py' from '/home/ghhc/miniconda3/envs/DyberPet/lib/python3.9/site-packages/PyInstaller/hooks'...
ldd: 警告：你没有执行权限  `/home/ghhc/miniconda3/envs/DyberPet/lib/python3.9/site-packages/PyQt5/QtNetwork.abi3.so'
8267 INFO: Loading module hook 'hook-PyQt5.py' from '/home/ghhc/miniconda3/envs/DyberPet/lib/python3.9/site-packages/PyInstaller/hooks'...
8267 WARNING: Hidden import "sip" not found!
8419 INFO: Looking for ctypes DLLs
8462 INFO: Analyzing run-time hooks ...
8467 INFO: Including run-time hook '/home/ghhc/miniconda3/envs/DyberPet/lib/python3.9/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pyqt5.py'
8468 INFO: Including run-time hook '/home/ghhc/miniconda3/envs/DyberPet/lib/python3.9/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pkgutil.py'
8470 INFO: Including run-time hook '/home/ghhc/miniconda3/envs/DyberPet/lib/python3.9/site-packages/PyInstaller/hooks/rthooks/pyi_rth_inspect.py'
8471 INFO: Including run-time hook '/home/ghhc/miniconda3/envs/DyberPet/lib/python3.9/site-packages/PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py'
8473 INFO: Including run-time hook '/home/ghhc/miniconda3/envs/DyberPet/lib/python3.9/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pkgres.py'
8490 INFO: Looking for dynamic libraries
ldd: 警告：你没有执行权限  `/home/ghhc/miniconda3/envs/DyberPet/lib/python3.9/site-packages/PyQt5/QtWidgets.abi3.so'
ldd: 警告：你没有执行权限  `/home/ghhc/miniconda3/envs/DyberPet/lib/python3.9/site-packages/PyQt5/QtCore.abi3.so'
ldd: 警告：你没有执行权限  `/home/ghhc/miniconda3/envs/DyberPet/lib/python3.9/site-packages/PyQt5/QtGui.abi3.so'
ldd: 警告：你没有执行权限  `/home/ghhc/miniconda3/envs/DyberPet/lib/python3.9/site-packages/PyQt5/QtMultimedia.abi3.so'
ldd: 警告：你没有执行权限  `/home/ghhc/miniconda3/envs/DyberPet/lib/python3.9/site-packages/PyQt5/QtNetwork.abi3.so'
ldd: 警告：你没有执行权限  `/home/ghhc/miniconda3/envs/DyberPet/plugins/imageformats/../../lib/libgcc_s.so.1'
10600 INFO: Looking for eggs
10600 INFO: Python library not among binary dependencies. Performing additional search...
10610 INFO: Using Python library /home/ghhc/miniconda3/envs/DyberPet/lib/libpython3.9.so.1.0
10616 INFO: Warnings written to /home/ghhc/Desktop/DyberPet/build/run_DyberPet/warn-run_DyberPet.txt
10644 INFO: Graph cross-reference written to /home/ghhc/Desktop/DyberPet/build/run_DyberPet/xref-run_DyberPet.html
10690 INFO: checking PYZ
10690 INFO: Building PYZ because PYZ-00.toc is non existent
10690 INFO: Building PYZ (ZlibArchive) /home/ghhc/Desktop/DyberPet/build/run_DyberPet/PYZ-00.pyz
10963 INFO: Building PYZ (ZlibArchive) /home/ghhc/Desktop/DyberPet/build/run_DyberPet/PYZ-00.pyz completed successfully.
10969 INFO: checking PKG
10969 INFO: Building PKG because PKG-00.toc is non existent
10969 INFO: Building PKG (CArchive) run_DyberPet.pkg
33190 INFO: Building PKG (CArchive) run_DyberPet.pkg completed successfully.
33200 INFO: Bootloader /home/ghhc/miniconda3/envs/DyberPet/lib/python3.9/site-packages/PyInstaller/bootloader/Linux-64bit-intel/run
33200 INFO: checking EXE
33200 INFO: Building EXE because EXE-00.toc is non existent
33200 INFO: Building EXE from EXE-00.toc
33205 INFO: Copying bootloader EXE to /home/ghhc/Desktop/DyberPet/dist/run_DyberPet
33206 INFO: Appending PKG archive to custom ELF section in EXE
33356 INFO: Building EXE from EXE-00.toc completed successfully.
`

```
运行日志：
```
'(DyberPet) ➜  DyberPet git:(main) ✗ /home/ghhc/Desktop/DyberPet/dist/run_DyberPet                             
/tmp/_MEIkiLdyM/data
Traceback (most recent call last):
  File "run_DyberPet.py", line 7, in <module>
    from DyberPet.DyberPet import PetWidget
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "DyberPet/DyberPet.py", line 39, in <module>
    settings.init()
  File "DyberPet/settings.py", line 87, in init
    pets = get_petlist(os.path.join(basedir, 'res/role'))
  File "DyberPet/settings.py", line 171, in get_petlist
    folders = os.listdir(dirname)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEIkiLdyM/res/role'
[37400] Failed to execute script 'run_DyberPet' due to unhandled exception!
'
```

**Comment by ChaozhongLiu** [comment]
这个打包应该没问题 问题出在代码里系统的判断上 我会尽快改正
