### ISSUE TITLE
v0.3.7 zip解压运行exe报错

### ISSUE THREAD

**Issue by ningwana** [ChaozhongLiu/DyberPet#23]
Traceback (most recent call last):
  File "run_DyberPet.py", line 170, in <module>
  File "run_DyberPet.py", line 74, in __init__
  File "DyberPet\DyberPet.py", line 362, in __init__
  File "DyberPet\DyberPet.py", line 1197, in init_conf
  File "DyberPet\DyberPet.py", line 730, in _set_menu
  File "DyberPet\custom_roundmenu.py", line 367, in addAction
  File "DyberPet\custom_roundmenu.py", line 194, in addItem
  File "DyberPet\custom_roundmenu.py", line 210, in adjustSize
  File "DyberPet\custom_roundmenu.py", line 784, in availableViewSize
AttributeError: 'NoneType' object has no attribute 'availableGeometry'

**Comment by ningwana** [comment]
跟这个有点雷同：https://github.com/zhiyiYo/PyQt-Fluent-Widgets/issues/253

**Comment by ChaozhongLiu** [comment]
我自己各种尝试没有复现出来，但是还是按照 PyQt-Fluent-Widgets最新版的RoundMenu进行更改了。
如果你有时间，麻烦在终端运行下看看是否已经解决了。感谢！

**Comment by ningwana** [comment]
@ChaozhongLiu 嗯嗯，刚运行了下，没问题了，原因可能是我是双屏导致。

还发现一个优化点，双屏情况下，宠物无法拖到另一个屏幕上...

**Comment by ChaozhongLiu** [comment]
啊这样么 双屏我是测试过的 我双屏的情况下可以自由拖动

**Comment by ChaozhongLiu** [comment]
能不能具体描述一下，比如两个屏幕是如何排列的、鼠标拖动到另一个屏幕的什么位置松手后会在边缘、“松手后在边缘”是指闪现到边缘么？

**Comment by ningwana** [comment]
1.比如两个屏幕是如何排列的、他们是镜像 (估计不行) 还是拓展 (可以)、
--------------
就是普通双屏，拓展排列。


2.鼠标拖动到另一个屏幕的什么位置松手后会在边缘、“松手后在边缘”是指闪现到边缘么？
------------
鼠标拖动宠物到另一个屏幕的任意位置，松手后宠物会自动闪现到那一块屏幕的边缘。


emmmmm，可能是我自己硬件的原因吧，如果你双屏可以自由拖动的话。

**Comment by ChaozhongLiu** [comment]
如果方便提供具体的设备信息的话 我可以看看是哪里出了问题～
