### ISSUE TITLE
检查更新

### ISSUE THREAD

**Issue by WT2024** [ChaozhongLiu/DyberPet#31]
#30 
我的意思是在软件内部可以直接更新，打开github的方式有些麻烦

**Comment by ChaozhongLiu** [comment]
这涉及到：
1. 更多的系统权限
2. 自架服务器：如果仍然使用 GitHub 作为文件来源，该慢还是慢，但我本来就毫无盈利，没有能力承担自家服务器的成本
3. 更多的代码，逻辑虽然简单，但是涉及诸多检查点和回溯

因此，我暂时没有计划编写直接更新的功能 （但如果你或者其他开发者愿意尝试解决，欢迎PR！）；更简单的方法是上架 Steam，由 steam 解决上述三个问题，因此正在计划之中。

**Comment by ChaozhongLiu** [comment]
也欢迎感兴趣的小伙伴进行尝试！

**Comment by WT2024** [comment]
让我康康应该怎么写

**Comment by Mashiro-Zhu** [comment]
========== RESTART: /Users/mashiro/Downloads/DyberPet/run_DyberPet.py ==========
Traceback (most recent call last):
  File "/Users/mashiro/Downloads/DyberPet/run_DyberPet.py", line 7, in <module>
    from DyberPet.DyberPet import PetWidget
  File "/Users/mashiro/Downloads/DyberPet/DyberPet/DyberPet.py", line 18, in <module>
    from qfluentwidgets import CaptionLabel, setFont, Action #,RoundMenu
ModuleNotFoundError: No module named 'qfluentwidgets'

我的一直在这里报错，我下载更新了也没用不知道哪里错了 macos的

**Comment by ChaozhongLiu** [comment]
@Mashiro-Zhu 请问你是下载的哪个文件，怎么会是在 Downloads 文件夹打开的

**Comment by Mashiro-Zhu** [comment]
> @Mashiro-Zhu 请问你是下载的哪个文件，怎么会是在 Downloads 文件夹打开的

我是直接下载的两个zip，DyberPet-main.zip 打开之后，然后run的那个py文件

**Comment by ChaozhongLiu** [comment]
> > @Mashiro-Zhu 请问你是下载的哪个文件，怎么会是在 Downloads 文件夹打开的
> 
> 我是直接下载的两个zip，DyberPet-main.zip 打开之后，然后run的那个py文件

不行哈，要去 [release](https://github.com/ChaozhongLiu/DyberPet/releases) 里找夸克网盘里的链接

**Comment by WT2024** [comment]
@ChaozhongLiu 我正在研究这个代码......搞不懂这个语言功能是怎么实现的

**Comment by WT2024** [comment]
是不是在某个文档里编好了固定单词的中文

**Comment by ChaozhongLiu** [comment]
你 PR 就用英文就好 翻译的问题我来搞定

**Comment by WT2024** [comment]
好的

**Comment by WT2024** [comment]
我先把代码搞懂

**Comment by ChaozhongLiu** [comment]
> 是不是在某个文档里编好了固定单词的中文

是的 Qt 的多语言模块 想了解我是怎么实现的可以[这行](https://github.com/ChaozhongLiu/DyberPet/blob/main/run_DyberPet.py#L52)看起： 
但是你不用管翻译问题的~

**Comment by WT2024** [comment]
好久没用Python了......

**Comment by WT2024** [comment]
我得已经一下

**Comment by Mashiro-Zhu** [comment]
> > > @Mashiro-Zhu 请问你是下载的哪个文件，怎么会是在 Downloads 文件夹打开的
> > 
> > 
> > 我是直接下载的两个zip，DyberPet-main.zip 打开之后，然后run的那个py文件
> 
> 不行哈，要去 [release](https://github.com/ChaozhongLiu/DyberPet/releases) 里找夸克网盘里的链接

能做个MAC的百度网盘链接的分享吗，我mac的笔记本 不知道为啥 没发下载更新夸克网盘 mac上只有百度网盘能用～

**Comment by ChaozhongLiu** [comment]
@Mashiro-Zhu B 站私信我 我加你联系方式给你发吧 我Mac刚好打不开百度网盘2333

**Comment by Mashiro-Zhu** [comment]
> @Mashiro-Zhu B 站私信我 我加你联系方式给你发吧 我Mac刚好打不开百度网盘2333

嗯嗯，好哒，麻烦了 up了哈哈，我刚刚b站私信你了～ただの夏バテ这是我的B站id
